name: build and test

on:
  push:
    branches: main
    paths:
      - 'Makefile'
      - '*.bash'
      - 'src/**/*'

env:
  CLANG_VERSION: 17

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - name: trust LLVM apt repositories
      run: wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
    - name: add LLVM apt repositories
      run: |
        sudo add-apt-repository --yes "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${CLANG_VERSION} main"
        sudo add-apt-repository --yes "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${CLANG_VERSION} main"
    - name: install clang
      run: sudo apt update --yes && sudo apt install --yes clang-${CLANG_VERSION} libc++-${CLANG_VERSION}-dev libc++abi-${CLANG_VERSION}-dev lld-${CLANG_VERSION}
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: matiaslindgren/advent-of-code-data
        token: ${{ secrets.read_aoc_data }}
        path: txt
    - run: make -j
    - run: make test_verbose
